dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- pytest --cov-report html:.reports/coverage --cov-config .coveragerc --cov-report term:skip-covered --cov=aioviber
after_success: coveralls
deploy:
  provider: pypi
  user: nonamenix
  password:
    secure: jN8s1Kc3jmO3XCtRw58QsRJLRtRPnfgakj7yNYYPH+Yvl9SMifSOcBdGWMp57spWIWGVQd6vDQltLaciBS1uPZK0PaoWD60m/KlQWmzFVMGeVwBJjyhgdD1UvkP5xTTlKDWuOawkPBVE32ibY1NWqACCYqMd5kvdmr/YcvM63h+KDIfPnrb1q77W6OSeiC9xTtPsYDvFzlgMOxkU0dfj+tEULtzLRFbKJ9mSq6QUvqALkxtq2OVVZiokmMuTQK+8dSNP+GYS/xBlycDpzNYmzMk/Po2jXmoe+J6/g/jD3QISGfn8Z2szst4iVHnwNoJMjQVtFGtORhPddDPKWmwz4wHXOI9SbckEjld3S/8PS1k29ujf7IiQbHnT31pWCl7MNJoBwBiRoEuDayPFIRf9OYCmbad2exkqJly/bzukuEr93WrWNEXne7Fb/01zzGKqVle+szXkqGSrZ9XoJR50I1hZ2/8SEZnwSW/35V2hNmJp285ohaPJ0huQvj8tX5V2wRCHRpiu1nXof7Ge4qzbn8SHYmOxzC6XDlOd3n5T1vkk0pDkFP7c0+28lIkS1dG+9ZvPxZ95jrjcmUkielwzALQMCwfm7rcjZLUw0eEYKxzeizI5D8LFT4O3TDn4KiSQOW2fXW5F79pUtXttiPQo93AlouRpi8i3leGg9p612Dk=
  on:
    distributions: sdist bdist_wheel
    repo: nonamenix/aioviber
    tags: true
